### ISSUE TITLE
Atom-like metadata items

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#101]
From #99. 

Atom metadata elements](https://tools.ietf.org/html/rfc4287#section-4.2) such as `title`, `rights`, `summary`, and `updated` are a useful extension of GeoJSON. The Atom elements are related to Dublin Core's but are fewer. Not all of Atom's are necessarily useful to GeoJSON.

Why `Feature.title` and not `Feature.properties.title`? First, a proposition: items added to `Feature.properties` do not make an extension. The `properties` object can contain anything, for better or worse. All the items have the same semi-anonymous context. GeoJSON processors can't assume any particular meaning for them [1]. If a GeoJSON processor encounters `Feature.properties.title` is it a OWSContext title? An Atom title? An NBA (National Basketball Association) title? Trying to make GeoJSON processors more clever about properties only makes the problem worse. If I modify, say, Mapbox.js (disclaimer: I work for Mapbox) so that it interprets any `Feature.properties.title` as an NBA title and adds an NBA logo in feature popups, I'll mess with or even break other GeoJSON applications. 

`Feature.title` on the other hand, is something that can be standardized in an extension and won't conflict with the vernacular in `Feature.properties`.

[1] without something like JSON-LD there are practically no semantics in `Feature.properties`.

**Comment by tkardi** [comment]
@sgillies I agree that any systematic metadata elements should not be merged into 'Feature.properties'. But maybe it would make more sense to make it more strict, say `Feature.atom` and `Feature.atom.title` or `FeatureCollection.atom.title`. Then the `atom` (or whatever it would be called) object can have a separate definition (as described for owscontext) and can be used at whatever level (FeatureCollection or Feature or Geometry)? Just like `type` is used currently. This way no existing implementations would break, and the original GeoJSON specification should be accounted for and kept "no-nonsense" simple but extended with metadata in an interoperable way.

**Comment by jyutzler** [comment]
I'd agree to Feature.atom.* and FeatureCollection.atom.*.

**Comment by dret** [comment]
while i think that adding some set of generic metadata items inspired by Atom is probably a good idea (and definitely worth exploring by the WG), i think my preference would be to not "namespace" them into something like `Feature.atom.*` or `FeatureCollection.atom.*` (and generally speaking, we should eat our own dogfood and simply follow the pattern that #59 recommends). that probably makes people think that there is something at work where they can have `Feature.myfavoritevocabulary.*` as well, and it will magically make additional vocabularies available.

**Comment by adoyle** [comment]
I think the question comes down to which authority is in charge of the “namespace”? Do we let anyone start using Feature.atom.* and risk having them do it wrong? Or do we define a few ourselves? Or do we reserve some of the names? What’s the responsible thing to do?

In my laissez faire world view, let the extenders extend, and let the better extensions win. That’s pretty much what we did with GeoJSON after all.

**Comment by roomthily** [comment]
Apologies if this has been discussed elsewhere, but would any of the proposed provide a reasonable way of validating the document with the additional chunk? The notion of validating one's metadata is tilting at windmills... Still, if it says Atom (or ISO or whatever), it'd be nice to verify that.

Cheers.

**Comment by dret** [comment]
On 2015-09-17 05:23, Sean Gillies wrote:
> First, a
> proposition: items added to |Feature.properties| do not make an
> extension. The |properties| object can contain anything, for better or
> worse. GeoJSON processors can't assume any particular meaning for them.
> If a GeoJSON processor encounters |Feature.properties.title| is it a
> OWSContext title? An Atom title? An NBA (National Basketball
> Association) title? Trying to make GeoJSON processors smarter about
> properties[1] only makes the problem worse. If I fork, say, Leaflet and
> modify it so that it interprets any |Feature.properties.title| as an NBA
> title and adds an NBA logo in feature popups, I'll break other GeoJSON
> applications.

while i think i understand what you're saying, i am wondering if that 
doesn't just go down the route of defining "extension extensions", and 
"non-extension extensions". what i mean by that is that clearly, if you 
find something that's not listed in the spec, somebody has been 
"extending" the core spec model with whatever it is that you're finding. 
not *calling* this an extension to me sounds a little bit confusing. 
what would those "non-extension properties" be called?

regardless of how the terminology question plays out, i think that this 
is another good data point that #15 has been raising: there probably 
should be some section that lists all these different ways in which 
non-core data can be added, so that implementers know what to expect. 
having examples for all of them (and a test suite containing them) might 
help with making sure that implementations handle and expose all the 
ways in which some GeoJSON might have non-core data in it.

**Comment by tkardi** [comment]
@dret:
> that probably makes people think that there is something at work where they can have Feature.myfavoritevocabulary.* as well, and it will magically make additional vocabularies available.

I totally agree. But I feel like I should clarify that I was talking about `Feature.atom` only because the title of this issue refers to atom-like metadata elements. But it could be anything - `Feature.meta` or `Feature.FluffyLittleKittens`. My point was that one specific key should be reserved for this.

**Comment by sgillies** [comment]
There's no consensus in the WG for standardizing metadata items (see https://mailarchive.ietf.org/arch/msg/geojson/J7P-rHTNzzdQJ_feTc4rutw4Rnw).
