### ISSUE TITLE
some paragraphs were replaced during porting from XML to Markdown

### ISSUE THREAD

**Issue by sir-sigurd** [geojson/draft-geojson#105]
This [commit](https://github.com/geojson/draft-geojson/commit/66b7942d75a906a3fce785e5c3dbc818707e96cd) replaces some paragraphs.
For example following paragraph was removed

```
On encountering a named CRS object with a value of
"urn:ogc:def:crs:OGC:1.3:CRS84" or
"http://www.opengis.net/def/crs/OGC/1.3/CRS84", processors SHOULD
interpret the coordinates exactly as in Section 2.1.1; these CRS are
equivalent to the default coordinate reference system.
```

It looks like this was caused by copy-pasting from some old version.

**Comment by adoyle** [comment]
My recollection is that this was a deliberate change.

**Comment by sir-sigurd** [comment]
@adoyle
I don't think so, because this change also adds reference to non-existant Section 3.1. You could see this reference here https://tools.ietf.org/html/draft-butler-geojson-06#section-6.4

**Comment by sgillies** [comment]
I did remove the paragraph because it felt superfluous, but I don't object to restoring it.

**Comment by adoyle** [comment]
This is an area we still have not completely come to grips with. Does restoring the omitted paragraph raise more questions than it answers? I prefer the wording as is because it's talking about an example, whereas this omitted wording is singling out a specific case. 

We do need to deal with the reference to 3.1. Maybe by just referring to section 3.

**Comment by sir-sigurd** [comment]
Actually I have no my own opinion on the text, I just found that non-working link and thought that text was replaced by accident. Sorry, if I was unclear on this.

**Comment by jyutzler** [comment]
Since the default behavior is to treat any unknown or undefined CRS as CRS84, I don't think putting in these examples is helpful. If a system provides a some other CRS, it is placing specific expectations on the receiving system. How to deal with systems that do not meet with those expectations is outside of the scope of GeoJSON.

**Comment by sgillies** [comment]
I'm reading https://github.com/geojson/draft-geojson/blob/master/considerations.mkd#coordinate-reference-system-identifiers and it makes no sense at all. draft-butler-geojson-06 *does not* recommend a change to HTTP URIs to identify CRS.

Would it be unreasonable to say in this interoperability section that there are two legacy CRS identifiers that GeoJSON processors may want to be aware of, and that if they encounter them in a GeoJSON document they don't need to freak out, but can go ahead with the understanding that they are equivalent to GeoJSON's default CRS?

**Comment by dret** [comment]
On 2015-10-20 14:11 , Sean Gillies wrote:
> I'm reading
> https://github.com/geojson/draft-geojson/blob/master/considerations.mkd#coordinate-reference-system-identifiers
> and it makes no sense at all. draft-butler-geojson-06 /does not/
> recommend a change to HTTP URIs to identify CRS.

https://tools.ietf.org/html/draft-butler-geojson-06#section-6.4 looks 
quite a bit as if it did. i agree that it would be better if it didn't 
(once you've decided on an identifier space and identifiers, changing 
either of those will cause a lot of breakage), but it does.

https://tools.ietf.org/html/draft-butler-geojson-06#section-6.4 has this 
broken link to 
https://tools.ietf.org/html/draft-butler-geojson-06#section-3.1, though, 
so maybe there's some cleanup to do?

**Comment by dret** [comment]
since we have now seen a call for adoption for https://tools.ietf.org/html/draft-butler-geojson-06, i am wondering how to address this issue? two questions:

* is anybody disagreeing that https://tools.ietf.org/html/draft-butler-geojson-06#section-6.4 currently has some text in it that it shouldn't have, namely something saying that URNs are deprecated, and a broken link to a non-existing section 3.1 of the same draft.

* if people agree with the above statement, what's the best way to fix it? i'd be happy to issue a pull request to fix that section, so that the adopted draft does not contain this (probably editing) error. anybody objecting to that?

**Comment by martinthomson** [comment]
@dret, if there are concerns, we should raise an issue on each to track it and then fix them as consensus demands.  If there is any contention, I suggest we take the discussion to the mailing list to hash out.

**Comment by dret** [comment]
agreed, @martinthomson, but i was simply trying to find out if anybody objected against the proposed resolution for this issue. i'll wait a little longer, and then create a PR.

**Comment by dret** [comment]
i tried to reconstruct what maybe -06 wanted to say but didn't, but -05 said the same thing. however, -04 was substantially different (in that particular spot, i.e. section 6). i think i have to give up at this point, since it seems to me that it's too difficulty from the draft and github history to reconstruct what maybe people wanted to change, and what actually ended up in the draft.
could we please have a specific discussion about what people think is simply wrong in -06, so that we can fix it before moving it to -00 of the WG track document? specifically, it's the broken reference to a section 3.1 and the claim that GeoJSON now recommends to use HTTP URIs for CRS identification.
thanks a lot!

**Comment by martinthomson** [comment]
I encourage people to:
1. Raise issues for specific defects (@dret has identified two here)
2. Send an email to geojson@ietf.org so that we can discuss them, if they are substantial. The CRS URI thing is substantial, I think.

**Comment by sgillies** [comment]
@dret @martinthomson the problem we have now is due to editorial errrors I made between -04 and -05.

See https://tools.ietf.org/rfcdiff?url2=draft-butler-geojson-05.txt.

The third paragraph was added by mistake. It has propagated into what is now, in -06, section 6.4. Removing 6.4 entirely resolves this issue and I will propose doing so on the geojson list.

**Comment by tschaub** [comment]
@sgillies I don't see an email on the list (perhaps you don't mean [the geojson list](http://lists.geojson.org/pipermail/geojson-geojson.org/)), but I agree with the proposal to remove [6.4](https://tools.ietf.org/html/draft-butler-geojson-06#section-6.4).

**Comment by sgillies** [comment]
List email here: https://mailarchive.ietf.org/arch/msg/geojson/_9gki5jWL8EPUd56HYysqKpTJvs.
