### ISSUE TITLE
Use °

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#176]
now that I-D and RFC documents are allowed to use non-ASCII symbols, it might be easier to read if the document used the ° symbol when talking about degrees.

**Comment by martinthomson** [comment]
I've asked about the non-ascii draft status.  This isn't something we can rely on now, and likely for a fairly long time; it's only in public comment period, after which there is some non-trivial amount of time.

Since this is something that can be addressed during AUTH48, I recommend that we proceed with "degrees" rather than "°".  It's more verbose, but not likely to stall on process.

**Comment by dret** [comment]
sounds good. fyi, here's the draft that's going to allow this (at some point in time):

https://tools.ietf.org/html/draft-flanagan-nonascii-04

**Comment by martinthomson** [comment]
Correction: https://tools.ietf.org/html/draft-iab-rfc-nonascii-01
