### ISSUE TITLE
Support Profiles

### ISSUE THREAD

**Issue by dret** [geojson/draft-geojson#97]
http://tools.ietf.org/html/rfc6906 defines a profile link relation type and also a model for how profiles can be signaled to data consumers.
it would be useful for GeoJSON to allow profiles, so that they can be used both in-band (the profile identifier being embedded in GeoJSON), and out-of-band (the profile identifier being used in external information such as an HTTP header or a media type parameter).
adding profile support would not (afaict) create any backwards-incompatibility. it would simply allow GeoJSON producers and consumers to have a more reliable way of signaling that some GeoJSON may follow additional rules/constraints and not just those of GeoJSON itself.

**Comment by dret** [comment]
for the embedded info, it could be something as simple as (needs to be refined, of course):
If a GeoJSON object has on its top level a member with a key "profile" and a string value, then this information should be treated as establishing a link from the GeoJSON object with the "profile" link relation, according to the model defined by RFC 6906.

**Comment by jyutzler** [comment]
The thing about profiles is that they aren't in any way self-describing. No naive system could possibly behave appropriately due to the presence of an unfamiliar profile. So what is the benefit of specifying the key/value pair that declares the profile? There is no potential interoperability to be gained here.  

I think it would be more beneficial for GeoJSON to support an explicit extension mechanism. It is at least plausible that a random profile uses extensions that a particular system just happens to support. The system doesn't care what profile was used when encoding the file, it just cares about what extensions (if any) are being used.

**Comment by dret** [comment]
> On Sep 9, 2015, at 11:19, Jeff Yutzler <notifications@github.com> wrote:
> The thing about profiles is that they aren't in any way self-describing.
> 
that's not quite true. they can be if you want them to be, but they were specifically designed to make this optional.

just serve whatever self-description format you prefer at the profile URI, and those interested in it can GET it.

> No naive system could possibly behave appropriately due to the presence of an unfamiliar profile.
> 
of course it can: it simply ignores it.
> So what is the benefit of specifying the key/value pair that declares the profile? There is no potential interoperability to be gained here.
> 
please refer to the spec; it explains the motivation, the design, and use cases.
> I think it would be more beneficial for GeoJSON to support an explicit extension mechanism. It is at least plausible that a random profile uses extensions that a particular system just happens to support. The system doesn't care what profile was used when encoding the file, it just cares about what extensions (if any) are being used.
> 
if you happen to define a self-description mechanism, just use it and use profiles to expose it. that way both scenarios work: extensions that have self-descriptions, and those that do not.

**Comment by jyutzler** [comment]
> they can be [self-describing] if you want them to be

Well, sure, using a self-describing mechanism that wouldn't be interpretable by a naive client because that mechanism isn't in the GeoJSON spec. That's not helpful.

I guess we're getting wrapped up in terminology. The spec defines profiles as:
> additional semantics that can be used to process a resource representation, such as constraints, conventions, extensions, or any other aspects that do not alter the basic media type semantics

If an extension is a type of profile then we're basically saying the same thing. I've never seen profiles used that way - what I usually see is a set of extensions and constraints that are defined to meet the needs of some community of interest. The constraints are generally uninteresting to me - the water people don't care what the aviation people are doing and vice versa. The extensions are potentially interesting because if they are both extending the same thing, they might as well do it the same way.

I'm not interested in the extension (profile) for self-describing extensions (profiles)!

**Comment by dret** [comment]
On 2015-09-09 13:21 , Jeff Yutzler wrote:
>     they can be [self-describing] if you want them to be
> Well, sure, using a self-describing mechanism that wouldn't be
> interpretable by a naive client because that mechanism isn't in the
> GeoJSON spec. That's not helpful.

why not? step 1 is being able to identify profiles. that's what the RFC 
describes, and what this issue is about. step 2 could be to describe 
profiles with some format, but for the sake of loose coupling and 
separation of concerns, that's something different.

it's similar to HTML-land. people have differing opinions on whether 
microformats, microdata, or RDFa are the way to go, but HTML itself was 
smart enough to stay out of this discussion. GeoJSON should do the same.

> If an extension is a type of profile then we're basically saying the
> same thing. I've never seen profiles used that way - what I usually see
> is a set of extensions and constraints that are defined to meet the
> needs of some community of interest. The constraints are generally
> uninteresting to me - the water people don't care what the aviation
> people are doing and vice versa. The extensions are potentially
> interesting because if they are both extending the same thing, they
> might as well do it the same way.

or not. they may have very different needs in how they deal with 
extensions. so let them figure out their mechanisms. that's what we have 
media types for.

> I'm not interested in the extension (profile) for self-describing
> extensions (profiles)!

that's not something you will have to do, no worries. if you think you 
know the one true way to describe profiles, write a spec, define a media 
type, and write clients that expect profile URIs to serve that media 
type and if that doesn't happen, the clients stop and complain. that's 
completely fine. others may go different routes. and that's fine, too.

btw, https://github.com/dret/GeoJSON-X is something that may be 
interesting in this context. it is a very simple way how to make GeoJSON 
*a bit* more self-describing. i would never claim that it's a general 
solution to all problems in this space. but for those who think 
GeoJSON-X is good enough, i am considering giving GeoJSON-X a profile 
URI so that people can mark some GeoJSON as using GeoJSON-X: 
https://github.com/dret/GeoJSON-X/issues/2

**Comment by dret** [comment]
just for completeness, it should be noted that if such a feature is added, it should be seen as part of the general model for extensibility #59; users would be allowed to use profile URIs to signify that they follow or request a profile, but that would be optional.

**Comment by dret** [comment]
restarting the discussion on the list: https://mailarchive.ietf.org/arch/msg/geojson/Axz-BRoEcGRqyJXkm408J2FsVzI

**Comment by dret** [comment]
no consensus on the list to take any action, so closing this issue without action.
