### ISSUE TITLE
Ban all extensions and profiles

### ISSUE THREAD

**Issue by mpdaly** [geojson/draft-geojson#98]
Click-bait title!

My problem with the core standard having *any mechanism at all* to enable or anoint extensions and/or profiles is that someone, somewhere *will use it*. Before you know it you will have the GeoJSON equivalent of [GeoSciML](http://www.geosciml.org) (etc, etc, etc): great for a certain domain of interest, with certain specific software, not that usable anywhere else.

**Any** extension mechanism offers **false hope**; a hope that you can stick a timestamp onto every coordinate and Leaflet or OpenLayers or whatever will be just fine with that; a hope that you can use polar coordinates referenced to some flagpole up some mountain, and your features will appear in the right place on Google Maps. False. False. **False**.

By all means use GeoJSON constructs in your JSON encoding. Stick a timestamp on every coordinate if you must. Go mad and make it lat/lon coordinate order (gasp!). Just don't call it GeoJSON, or believe that it is usable in software that was developed against the core standard.

Please let's not pretend that there exists some magic fairy dust that will make that not-GeoJSON, actual-GeoJSON.

cc: @geojson/owners

**Comment by prushforth** [comment]
+1 .  The internet has an extensibility mechanism built in: mime types.  If you want to create a new one, using GeoJSON as  a base, that is the way to go about it.  If people use your mime type to describe (self-describe) their
content, and not application/geojson+json (or whatever it is), then they know what they’re doing.

**Comment by dret** [comment]
do we have any data on how much of the GeoJSON out there uses what's currently allowed in terms of extensibility? disallowing any extensions would break all of it.
and of course, if software breaks when encountering such an extension, that software is broken.

**Comment by dret** [comment]
@prushforth, that's where profiles #97 are handy; they allow you to say (on the media type level!) that what you're doing follows an additional set of rules (if somebody is interested in that set), but that it *also* follows basic GeoJSON rules and can be treated as GeoJSON by any conforming implementation.

**Comment by mpdaly** [comment]
@dret, No data that I know of, but I'd be happy to look at any that anyone has. As far as I recall the only "extension" allowed is extra numbers in coordinates, and I've never seen that in the wild myself.

A "we used to allow this but we don't now" clause, as per non-WGS84 CRSs, would cover that off as far as I am concerned.

Profiles are simply a mechanism. I'm proposing a principle.

**Comment by prushforth** [comment]
@dret As you know, I have used them.  I have come to think that parsing media type strings on parameters is difficult, and not worth the effort (not supported by libraries) over using a custom (registered or not) string.   Furthermore that forces us to take ownership for the semantics in the document.    I also think the '+json' / '+xml' convention is (similarly) misguided and non-functional.  YMMV

**Comment by jyutzler** [comment]
I see the lack of a deliberate extension mechanism GeoJSON's biggest weakness, you see it as GeoJSON's biggest strength. *sigh* People are going to extend GeoJSON whether you like it or not*. How does encouraging the Wild West help matters? It should be self-evident that a minimally compliant client must not be expected to understand anything but the core. So what are you afraid of? What is the harm of declaring the extensions that are in a GeoJSON document, in the off chance that a client can take advantage of their benefits?

* Is TopoJSON a GeoJSON extension? (If not, then I expect to see a cease and desist letter.) Having to duck type a document to figure out if it is TopoJSON is annoying at best.

**Comment by mpdaly** [comment]
@jyutzler 

> By all means use GeoJSON constructs in your JSON encoding. Stick a timestamp on every
> coordinate if you must. Go mad and make it lat/lon coordinate order (gasp!). Just don't call it
> GeoJSON, or believe that it is usable in software that was developed against the core standard.

**Comment by dret** [comment]
On 2015-09-10 7:45 , Martin Daly wrote:
> *Any* extension mechanism offers *false hope*; a hope that you can stick
> a timestamp onto every coordinate and Leaflet or OpenLayers or whatever
> will be just fine with that; a hope that you can use polar coordinates
> referenced to some flagpole up some mountain, and your features will
> appear in the right place on Google Maps. False. False. *False*.

i think you're mixing two things here. extension models, when done well, 
are powerful and can increase success and traction tremendously. which 
is why we're having this discussion.

let's look at your examples:

- timestamps: iff that's an allowed extension (let's assume they're 
numbers), and the spec had a clear "processing model" section saying 
what extension places exist, then any implementer should be able to 
create a non-broken implementation. test datasets *leveraging all 
well-defined extension points* can help tremendously so that 
implementers know what to expect and have something to test against.

- coordinates: extension should never be allowed to change the semantics 
of the core model (essentially implementing "mustUnderstand" semantics, 
which are very fragile). because that is, i agree, a recipe for 
disaster. but again, that's something that a well-defined extension 
model would clearly specify (extensions must use "mustIgnore").

wrt to the latter: https://tools.ietf.org/html/rfc6906#section-3 says 
the following:

"A profile MUST NOT change the semantics of the resource representation 
when processed without profile knowledge, so that clients both with and 
without knowledge of a profiled resource can safely use the same 
representation."

let me get out of this permathread with this final remark: whatever it 
is that the community comes up with as an extension model (including 
"none at all", removing the current extensibility), i think there should 
be an explicit section about that, including a processing model, so that 
implementers can find guidance in one place.
